# Generated by Django 4.2.29 on 2026-04-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_status_valid',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('partially_paid', 'Partially Paid')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partially_paid', 'Partially Paid')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['unpaid', 'paid', 'overdue', 'cancelled', 'partially_paid'])), name='invoice_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'complete', 'failed', 'cancelled', 'partially_paid'])), name='payment_status_valid'),
        ),
    ]
