# Generated by Django 4.2.29 on 2026-03-29 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("secondname", models.CharField(max_length=100)),
                ("phonenumber", models.CharField(max_length=20)),
                ("workemail", models.EmailField(max_length=254)),
                ("jobtitle", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=100)),
                (
                    "categories",
                    models.CharField(
                        choices=[
                            ("education", "Education"),
                            ("corporate", "Corporate"),
                            ("government", "Government"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("institution_name", models.CharField(max_length=255)),
                ("size_of_institution", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "question_on_preference",
                    models.CharField(
                        choices=[
                            ("social_media", "Social Media"),
                            ("email", "Email"),
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("demo_scheduled", "Demo Scheduled"),
                            ("negotiated", "Negotiated"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "db_table": "leads",
            },
        ),
        migrations.CreateModel(
            name="DemoSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("physical", "Physical"), ("online", "Online")],
                        max_length=20,
                    ),
                ),
                ("meeting_link", models.URLField(blank=True, null=True)),
                ("place", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "demo_type",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("physical", "Physical"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "demo_status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leads.lead"
                    ),
                ),
            ],
            options={
                "verbose_name": "Demo Schedule",
                "verbose_name_plural": "Demo Schedules",
                "db_table": "demo_schedules",
            },
        ),
        migrations.CreateModel(
            name="Onboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inprogress", "In Progress"),
                            ("completed", "Completed"),
                            ("onhold", "On Hold"),
                        ],
                        default="inprogress",
                        max_length=20,
                    ),
                ),
                ("startdate", models.DateField()),
                ("expected_go_live_date", models.DateField()),
                ("actual_go_live_date", models.DateField(blank=True, null=True)),
                (
                    "onboarding_type",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("physical", "Physical"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("percentage", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "onboarding_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding",
                "verbose_name_plural": "Onboardings",
                "db_table": "onboardings",
                "indexes": [
                    models.Index(
                        fields=["school"], name="onboardings_school__d1d00a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="onboardings_status_52e0f7_idx"
                    ),
                    models.Index(
                        fields=["onboarding_manager"],
                        name="onboardings_onboard_afdb58_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_lead", "New Lead"),
                            ("demo_reminder", "Demo Reminder"),
                            ("lead_assigned", "Lead Assigned"),
                            ("status_changed", "Status Changed"),
                            ("demo_completed", "Demo Completed"),
                            ("onboarding_update", "Onboarding Update"),
                        ],
                        default="new_lead",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "indexes": [
                    models.Index(
                        fields=["user"], name="notificatio_user_id_e78525_idx"
                    ),
                    models.Index(
                        fields=["is_read"], name="notificatio_is_read_3f8c44_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("lead_created", "Lead Created"),
                            ("lead_assigned", "Lead Assigned"),
                            ("demo_scheduled", "Demo Scheduled"),
                            ("lead_converted", "Lead Converted"),
                            ("onboarding_started", "Onboarding Started"),
                            ("onboarding_completed", "Onboarding Completed"),
                            ("school_live", "School Live"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="leads.lead",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "db_table": "logs",
                "indexes": [
                    models.Index(fields=["lead"], name="logs_lead_id_84ccd7_idx"),
                    models.Index(fields=["user"], name="logs_user_id_1f4728_idx"),
                    models.Index(fields=["log_type"], name="logs_log_typ_2f6492_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["workemail"], name="leads_workema_d21f4a_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status"], name="leads_status_94f025_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["assigned_staff"], name="leads_assigne_f3e85b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["categories"], name="leads_categor_e2aa7b_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["country"], name="leads_country_92c91a_idx"),
        ),
        migrations.AddIndex(
            model_name="demoschedule",
            index=models.Index(fields=["lead"], name="demo_schedu_lead_id_d75119_idx"),
        ),
        migrations.AddIndex(
            model_name="demoschedule",
            index=models.Index(
                fields=["assigned_staff"], name="demo_schedu_assigne_f39869_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="demoschedule",
            index=models.Index(fields=["date"], name="demo_schedu_date_d3c4b6_idx"),
        ),
    ]
