# Generated by Django 6.0.1 on 2026-03-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="credittop",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_tops",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="emailverificationtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verification_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auth_sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(fields=["name"], name="plans_name_98fd02_idx"),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(fields=["plan_id"], name="plans_plan_id_6ef534_idx"),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(fields=["use_type"], name="plans_use_typ_11595e_idx"),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(fields=["is_active"], name="plans_is_acti_85d1d6_idx"),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(fields=["is_popular"], name="plans_is_popu_51cf59_idx"),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.CheckConstraint(
                condition=models.Q(("use_type__in", ["individual", "enterprise"])),
                name="plan_use_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_price__gte", 0)),
                name="monthly_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.CheckConstraint(
                condition=models.Q(("annual_price__gte", 0)),
                name="annual_price_non_negative",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Subscription plan for this user (legacy auth)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="authentication.plan",
            ),
        ),
        migrations.AddField(
            model_name="planfeature",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="authentication.plan",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.plan"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="credittop",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_tops",
                to="authentication.subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["email"], name="auth_invita_email_776a54_idx"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["token"], name="auth_invita_token_ed0339_idx"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["used"], name="auth_invita_used_793096_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_type"], name="users_user_ty_578f8f_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organisation"], name="users_organis_3b1f1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user_type", "individual"),
                    models.Q(
                        ("user_type", "enterprise"), ("organisation__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="enterprise_user_must_have_organisation",
            ),
        ),
        migrations.AddIndex(
            model_name="planfeature",
            index=models.Index(fields=["plan"], name="plan_featur_plan_id_be791d_idx"),
        ),
        migrations.AddIndex(
            model_name="planfeature",
            index=models.Index(
                fields=["included"], name="plan_featur_include_4309f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="subscriptio_status_572d44_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["plan"], name="subscriptio_plan_id_79f098_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["user"], name="subscriptio_user_id_aa8bc6_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["organisation"], name="subscriptio_organis_00600e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("organisation__isnull", True)),
                    models.Q(("user__isnull", True), ("organisation__isnull", False)),
                    _connector="OR",
                ),
                name="subscription_belongs_to_user_or_organisation",
            ),
        ),
        migrations.AddIndex(
            model_name="credittop",
            index=models.Index(
                fields=["subscription"], name="credit_tops_subscri_d688c0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="credittop",
            constraint=models.CheckConstraint(
                condition=models.Q(("credit_add__gt", 0)), name="credit_add_positive"
            ),
        ),
    ]
