# Generated by Django 4.2.29 on 2026-04-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='enterprise_user_must_have_organisation',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('user_type', 'individual'), ('user_type', 'nibble'), models.Q(('user_type', 'enterprise'), ('organisation__isnull', False)), _connector='OR'), name='enterprise_user_must_have_organisation'),
        ),
    ]
