# Generated by Django 4.2.29 on 2026-04-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_enterprise_user_must_have_organisation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['display_order', 'plan_id'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
        migrations.AddField(
            model_name='plan',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which this plan should be displayed'),
        ),
    ]
