# Generated by Django 6.0.1 on 2026-03-15 19:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("school_email", models.EmailField(max_length=254, unique=True)),
                ("max_students", models.IntegerField()),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("teacher_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_user",
                    models.OneToOneField(
                        blank=True,
                        help_text="School admin user linked to this school",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_school",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_schools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school",
                        to="authentication.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "db_table": "schools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("school_admin", "School Admin"),
                        ],
                        default="teacher",
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
                "db_table": "school_invitations",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("school_email", models.EmailField(max_length=254)),
                (
                    "student_code",
                    models.CharField(
                        help_text="Unique code per school (3-10 characters)",
                        max_length=10,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "students",
                "ordering": ["school", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tool", models.CharField(max_length=100)),
                ("request_count", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="schools.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Log",
                "verbose_name_plural": "Usage Logs",
                "db_table": "usage_logs",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("school_email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("school_admin", "School Admin"),
                        ],
                        default="teacher",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
                "db_table": "staff",
                "ordering": ["school", "last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["school", "school_email"],
                        name="staff_school__3b1502_idx",
                    ),
                    models.Index(fields=["is_active"], name="staff_is_acti_e9a75c_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "school_email"),
                        name="unique_staff_email_per_school",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school", "student_code"], name="students_school__fb7297_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school", "school_email"], name="students_school__f37377_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["is_active"], name="students_is_acti_4aecc9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("school", "student_code"), name="unique_student_code_per_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("school", "school_email"), name="unique_email_per_school"
            ),
        ),
        migrations.AddIndex(
            model_name="usagelog",
            index=models.Index(
                fields=["student", "created_at"], name="usage_logs_student_8f203e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagelog",
            index=models.Index(
                fields=["school", "created_at"], name="usage_logs_school__ff1ac2_idx"
            ),
        ),
    ]
