# Generated by Django 4.2.29 on 2026-03-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="org_orientation",
            field=models.BooleanField(default=False),
        ),
    ]
