# Generated by Django 4.2.29 on 2026-03-29 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="Model identifier e.g. 'gpt-4o-mini'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human readable name", max_length=100),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("deepseek", "DeepSeek")],
                        default="openai",
                        max_length=20,
                    ),
                ),
                (
                    "input_token_weight",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
                ),
                (
                    "output_token_weight",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
                ),
                (
                    "min_charge",
                    models.IntegerField(
                        default=50,
                        help_text="Minimum credits for any request with this model",
                    ),
                ),
                (
                    "credit_multiplier",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
                ),
                (
                    "enterprise_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.2,
                        help_text="Discount for enterprise users (e.g. 0.20 for 20%)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Model Config",
                "verbose_name_plural": "AI Model Configs",
                "db_table": "ai_model_configs",
            },
        ),
        migrations.CreateModel(
            name="AITool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier generated from the name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("student_friendly_name", models.CharField(max_length=255)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "color",
                    models.CharField(
                        default="#000000", help_text="Hex color code", max_length=7
                    ),
                ),
                ("system_prompt", models.TextField(blank=True, null=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("is_recommended", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "preferred_modal",
                    models.CharField(
                        blank=True,
                        help_text="Preferred AI modal for this tool, e.g. 'gpt-4', 'deepseek-chat'",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Tool",
                "verbose_name_plural": "AI Tools",
                "db_table": "ai_tools",
            },
        ),
        migrations.CreateModel(
            name="ToolCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon name for frontend display",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("teacher", "Teacher"), ("student", "Student")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tool Category",
                "verbose_name_plural": "Tool Categories",
                "db_table": "tool_categories",
            },
        ),
        migrations.CreateModel(
            name="UserAIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_requests", models.IntegerField(default=0)),
                ("total_tokens", models.BigIntegerField(default=0)),
                (
                    "total_credits",
                    models.BigIntegerField(
                        default=0, help_text="Total internal credits spent"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_request_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User AI Usage",
                "verbose_name_plural": "User AI Usage",
                "db_table": "user_ai_usage",
            },
        ),
        migrations.CreateModel(
            name="ToolInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("dropdown", "Dropdown"),
                            ("textarea", "Textarea"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "placeholder",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "default_value",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True, help_text="For dropdown: list of options", null=True
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("minlength", models.IntegerField(blank=True, null=True)),
                ("maxlength", models.IntegerField(blank=True, null=True)),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Display order of inputs"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="tools.aitool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Input",
                "verbose_name_plural": "Tool Inputs",
                "db_table": "tool_inputs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tools.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="aitool",
            name="categories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tools",
                to="tools.toolcategory",
            ),
        ),
        migrations.CreateModel(
            name="ToolFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="tools.aitool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_tools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Favorite",
                "verbose_name_plural": "Tool Favorites",
                "db_table": "tool_favorites",
                "unique_together": {("user", "tool")},
            },
        ),
        migrations.CreateModel(
            name="AILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool", models.CharField(max_length=50)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("topic", models.CharField(blank=True, max_length=255, null=True)),
                ("class_level", models.CharField(blank=True, max_length=50, null=True)),
                ("difficulty", models.CharField(blank=True, max_length=50, null=True)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "credits",
                    models.IntegerField(
                        default=0, help_text="Credits deducted from the user"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Actual dollar cost (internal tracking)",
                        max_digits=10,
                    ),
                ),
                ("inputs", models.JSONField(blank=True, null=True)),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("deepseek", "DeepSeek")],
                        default="openai",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, help_text="Response time in seconds", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Log",
                "verbose_name_plural": "AI Logs",
                "db_table": "ai_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="ai_logs_created_1f60a4_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ai_logs_user_id_cc8ccf_idx",
                    ),
                    models.Index(
                        fields=["tool", "-created_at"], name="ai_logs_tool_f43265_idx"
                    ),
                    models.Index(
                        fields=["provider", "-created_at"],
                        name="ai_logs_provide_75951f_idx",
                    ),
                ],
            },
        ),
    ]
