# Generated by Django 4.2.29 on 2026-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='user_prompt_template',
            field=models.TextField(blank=True, help_text='Template for the user prompt with placeholders like {column_name}', null=True),
        ),
    ]
